[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:celery]
command=celery -A RBAC worker -c 4 --loglevel=info
directory= .
autostart=true
autorestart=true
# stdout_logfile=/tmp/celery.log
# stderr_logfile=/tmp/celery.err

[program:gunicorn]
command=gunicorn RBAC.wsgi:application --bind 0.0.0.0:8080
directory= .
autostart=true
autorestart=true
# stdout_logfile=/tmp/gunicorn.log
# stderr_logfile=/tmp/gunicorn.err
