name: Django CI/CD Pipeline

on:
  push:
    branches: [work]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        DEBUG: ${{ secrets.DEBUG }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: '*'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for all branches

      - name: Set up Git identity
        run: |
          git config --global user.name 'Dada Oluwatimileyin'
          git config --global user.email 'oluwatimileyin962@gmail.com'

      - name: Ensure master is up-to-date
        run: |
          git checkout master
          git pull origin master  # Ensure master is up-to-date with remote

      - name: Fetch work branch
        run: |
          git fetch origin work  # Fetch the latest `work` branch from the remote

      - name: Merge work into master
        run: |
          git checkout master
          git merge --strategy-option=theirs origin/work --no-ff --no-edit --allow-unrelated-histories

      - name: Push changes to master
        run: |
          git push origin master