name: Django CI/CD Pipeline

on:
  push:
    branches: [work]


jobs:
  test:
    runs-on: ubuntu-latest
    env:
        DEBUG: ${{ secrets.DEBUG }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: '*'
    strategy:
      max-parallel: 4
      matrix:
        python-version: '3.10'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Fetch all branches
        run: |
          git fetch origin

      - name: Checkout work branch
        run: |
          git checkout work

      - name: Merge work into master
        run: |
          git checkout master
          git config --global user.name 'Dada Oluwatimileyin'
          git config --global user.email 'oluwatimileyin962@gmail.com'
          git merge -X theirs work --no-ff --no-edit --allow-unrelated-histories

      - name: Push changes to main
        run: |
          git push origin master
